# src/main/resources/application.yml
spring:
    config:
        import:
            - optional:classpath:application-secret.yml  # 시크릿 분리 파일
    application:
        name: lumicore

    datasource:
        url: "jdbc:mysql://localhost:3306/lumidiary
          ?serverTimezone=Asia/Seoul
          &characterEncoding=utf8
          &useSSL=false
          &allowPublicKeyRetrieval=true
          &createDatabaseIfNotExist=true" #"jdbc:mysql://10.0.10.210:3306/lumidiary
        username: ${spring.datasource.username}       # 플레이스홀더
        password: ${spring.datasource.password}       # 플레이스홀더
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true

    batch:
        jdbc:
            initialize-schema: always
            isolation-level-for-create: default
            platform: mysql
            schema: classpath:org/springframework/batch/core/schema-mysql.sql
        job:
            enabled: false  # 시작시 Job 자동실행 비활성화
            name: ${job.name:NONE}

app:
    client:
        url: "api.lumidiary.com"

oci:
    tenancy:
        ocid: ${OCI_TENANCY_OCID}           # 환경변수 또는 CI/CD 시크릿으로 주입
    user:
        ocid: ${OCI_USER_OCID}
    fingerprint: ${OCI_FINGERPRINT}         # API 키 지문
    keyFile: ${OCI_KEY_FILE}                # ex: /home/you/.oci/oci_api_key.pem
    keyPassphrase: ${OCI_KEY_PASSPHRASE:}   # 비밀번호 없으면 빈 문자열
    region: ${OCI_REGION:ap-chuncheon-1}    # 기본 리전
    configFilePath: ${OCI_CONFIG_FILE:${user.home}/.oci/config}  # OCI 설정 파일 경로

    objectstorage:
        namespace: ax5ipvulwvc1             # OCI Object Storage namespace
        bucket: bucket-20250507-1731        # OCI Object Storage bucket 이름
        uri-prefix: https://ax5ipvulwvc1.objectstorage.ap-chuncheon-1.oci.customer-oci.com
    queue:
        id: ocid1.queue.oc1.ap-chuncheon-1.amaaaaaabtgrhfyaiwmflsupo2zjy2xlyqdvbvsh2i54jdqctcfaumybytaq
        channels:
            default: diary    # 기존 메시지용 채널 ID
            digest: digest    # Digest 전용 채널 ID

logging:
    level:
        root: INFO
        com.example.lumicore: DEBUG
        com.example.lumicore.service: DEBUG
        com.example.lumicore.config: DEBUG
        com.example.lumicore.websocket: DEBUG
        org.springframework.web.socket: DEBUG
        org.springframework.security.web.FilterChainProxy: DEBUG
        org.springframework.security.config: DEBUG
        org.springframework.batch: DEBUG  # Spring Batch 로깅 추가




