---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-service
  labels:
    app: diary-service
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: diary-service
  template:
    metadata:
      labels:
        app: diary-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      volumes:
        - name: oci-config
          secret:
            secretName: oci-config-secret
      containers:
        - name: diary-service
          image: jangwoojung/diary-service:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: oci-config
              mountPath: /root/.oci
              readOnly: true
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: diary-service
spec:
  selector:
    app: diary-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP