apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-service
  labels:
    app: diary-service
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: diary-service
  template:
    metadata:
      labels:
        app: diary-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      # ──────────────── Secret을 마운트할 volumes 추가 ────────────────
      volumes:
        - name: oci-config-volume
          secret:
            secretName: oci-config-secret
            items:
              - key: config
                path: config
              - key: oci_api_private_key.pem
                path: oci_api_private_key.pem

      containers:
        - name: diary-service
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8082

          # ──────────────── 마운트 지점(volumeMounts) 추가 ────────────────
          volumeMounts:
            - name: oci-config-volume
              mountPath: /root/.oci
              readOnly: true

          env:
            # ──────────────── DB 관련 환경 변수 ────────────────
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: DB_USERNAME
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: DB_PASSWORD

            # ──────────────── OCI STREAM 관련 환경 변수 ────────────────
            - name: OCI_TENANCY
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_TENANCY
            - name: OCI_USER
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_USER
            - name: OCI_STREAM_POOL_OCID
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_POOL_OCID
            - name: OCI_STREAM_BROKERS
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_BROKERS
            - name: OCI_STREAM_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_AUTH_TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: diary-service
spec:
  selector:
    app: diary-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP
