apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-service
  labels:
    app: diary-service
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: diary-service
  template:
    metadata:
      labels:
        app: diary-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: diary-service
          image: jangwoojung/diary-service:latest
          ports:
            - containerPort: 8080
          env:
            # DB
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: DB_USERNAME
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: DB_PASSWORD

            # OCI STREAM ENV
            - name: OCI_TENANCY
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_TENANCY
            - name: OCI_USER
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_USER
            - name: OCI_STREAM_POOL_OCID
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_POOL_OCID
            - name: OCI_STREAM_BROKERS
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_BROKERS
            - name: OCI_STREAM_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: diary-app-secret
                  key: OCI_STREAM_AUTH_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: diary-service
spec:
  selector:
    app: diary-service
  ports:
    - port: 80
      targetPort: 8082
  type: ClusterIP